<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>message</artifactId>
        <groupId>com.ordering</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>message-biz</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>
        message 模块，模板消息 websocket 推送消息等等
    </description>

    <dependencies>
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>message-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>member-biz</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 业务组件 -->
<!--        <dependency>-->
<!--            <groupId>com.ordering</groupId>-->
<!--            <artifactId>app-spring-boot-starter-biz-operatelog</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-tenant</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-security</artifactId>
        </dependency>


        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-redis</artifactId>
        </dependency>


        <!-- 消息队列相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-mq</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-excel</artifactId>
        </dependency>



    </dependencies>

</project>
