<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ordering</groupId>
        <artifactId>backend</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>delivery-biz</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>
        delivery 模块 - 无人机配送业务
    </description>

    <dependencies>
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>delivery-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 业务组件 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-tenant</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-redis</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>com.ordering</groupId>
            <artifactId>starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
